/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scf_eda.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "scf_eda.pb-c.h"
void   scf_line__init
                     (ScfLine         *message)
{
  static ScfLine init_value = SCF_LINE__INIT;
  *message = init_value;
}
size_t scf_line__get_packed_size
                     (const ScfLine *message)
{
  assert(message->base.descriptor == &scf_line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scf_line__pack
                     (const ScfLine *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scf_line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scf_line__pack_to_buffer
                     (const ScfLine *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scf_line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfLine *
       scf_line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfLine *)
     protobuf_c_message_unpack (&scf_line__descriptor,
                                allocator, len, data);
}
void   scf_line__free_unpacked
                     (ScfLine *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scf_line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scf_epin__init
                     (ScfEpin         *message)
{
  static ScfEpin init_value = SCF_EPIN__INIT;
  *message = init_value;
}
size_t scf_epin__get_packed_size
                     (const ScfEpin *message)
{
  assert(message->base.descriptor == &scf_epin__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scf_epin__pack
                     (const ScfEpin *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scf_epin__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scf_epin__pack_to_buffer
                     (const ScfEpin *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scf_epin__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEpin *
       scf_epin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEpin *)
     protobuf_c_message_unpack (&scf_epin__descriptor,
                                allocator, len, data);
}
void   scf_epin__free_unpacked
                     (ScfEpin *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scf_epin__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scf_econn__init
                     (ScfEconn         *message)
{
  static ScfEconn init_value = SCF_ECONN__INIT;
  *message = init_value;
}
size_t scf_econn__get_packed_size
                     (const ScfEconn *message)
{
  assert(message->base.descriptor == &scf_econn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scf_econn__pack
                     (const ScfEconn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scf_econn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scf_econn__pack_to_buffer
                     (const ScfEconn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scf_econn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEconn *
       scf_econn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEconn *)
     protobuf_c_message_unpack (&scf_econn__descriptor,
                                allocator, len, data);
}
void   scf_econn__free_unpacked
                     (ScfEconn *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scf_econn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scf_eline__init
                     (ScfEline         *message)
{
  static ScfEline init_value = SCF_ELINE__INIT;
  *message = init_value;
}
size_t scf_eline__get_packed_size
                     (const ScfEline *message)
{
  assert(message->base.descriptor == &scf_eline__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scf_eline__pack
                     (const ScfEline *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scf_eline__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scf_eline__pack_to_buffer
                     (const ScfEline *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scf_eline__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEline *
       scf_eline__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEline *)
     protobuf_c_message_unpack (&scf_eline__descriptor,
                                allocator, len, data);
}
void   scf_eline__free_unpacked
                     (ScfEline *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scf_eline__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scf_ecomponent__init
                     (ScfEcomponent         *message)
{
  static ScfEcomponent init_value = SCF_ECOMPONENT__INIT;
  *message = init_value;
}
size_t scf_ecomponent__get_packed_size
                     (const ScfEcomponent *message)
{
  assert(message->base.descriptor == &scf_ecomponent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scf_ecomponent__pack
                     (const ScfEcomponent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scf_ecomponent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scf_ecomponent__pack_to_buffer
                     (const ScfEcomponent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scf_ecomponent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEcomponent *
       scf_ecomponent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEcomponent *)
     protobuf_c_message_unpack (&scf_ecomponent__descriptor,
                                allocator, len, data);
}
void   scf_ecomponent__free_unpacked
                     (ScfEcomponent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scf_ecomponent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scf_efunction__init
                     (ScfEfunction         *message)
{
  static ScfEfunction init_value = SCF_EFUNCTION__INIT;
  *message = init_value;
}
size_t scf_efunction__get_packed_size
                     (const ScfEfunction *message)
{
  assert(message->base.descriptor == &scf_efunction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scf_efunction__pack
                     (const ScfEfunction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scf_efunction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scf_efunction__pack_to_buffer
                     (const ScfEfunction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scf_efunction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEfunction *
       scf_efunction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEfunction *)
     protobuf_c_message_unpack (&scf_efunction__descriptor,
                                allocator, len, data);
}
void   scf_efunction__free_unpacked
                     (ScfEfunction *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scf_efunction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scf_eboard__init
                     (ScfEboard         *message)
{
  static ScfEboard init_value = SCF_EBOARD__INIT;
  *message = init_value;
}
size_t scf_eboard__get_packed_size
                     (const ScfEboard *message)
{
  assert(message->base.descriptor == &scf_eboard__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scf_eboard__pack
                     (const ScfEboard *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scf_eboard__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scf_eboard__pack_to_buffer
                     (const ScfEboard *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scf_eboard__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScfEboard *
       scf_eboard__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScfEboard *)
     protobuf_c_message_unpack (&scf_eboard__descriptor,
                                allocator, len, data);
}
void   scf_eboard__free_unpacked
                     (ScfEboard *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scf_eboard__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor scf_line__field_descriptors[4] =
{
  {
    "x0",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfLine, x0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y0",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfLine, y0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x1",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfLine, x1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y1",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfLine, y1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scf_line__field_indices_by_name[] = {
  0,   /* field[0] = x0 */
  2,   /* field[2] = x1 */
  1,   /* field[1] = y0 */
  3,   /* field[3] = y1 */
};
static const ProtobufCIntRange scf_line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor scf_line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scf_line",
  "ScfLine",
  "ScfLine",
  "",
  sizeof(ScfLine),
  4,
  scf_line__field_descriptors,
  scf_line__field_indices_by_name,
  1,  scf_line__number_ranges,
  (ProtobufCMessageInit) scf_line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scf_epin__field_descriptors[7] =
{
  {
    "tos",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ScfEpin, n_tos),
    offsetof(ScfEpin, tos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, cid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lid",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, lid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEpin, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scf_epin__field_indices_by_name[] = {
  2,   /* field[2] = cid */
  4,   /* field[4] = flags */
  1,   /* field[1] = id */
  3,   /* field[3] = lid */
  0,   /* field[0] = tos */
  5,   /* field[5] = x */
  6,   /* field[6] = y */
};
static const ProtobufCIntRange scf_epin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor scf_epin__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scf_epin",
  "ScfEpin",
  "ScfEpin",
  "",
  sizeof(ScfEpin),
  7,
  scf_epin__field_descriptors,
  scf_epin__field_indices_by_name,
  1,  scf_epin__number_ranges,
  (ProtobufCMessageInit) scf_epin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scf_econn__field_descriptors[2] =
{
  {
    "lid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEconn, lid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ScfEconn, n_cids),
    offsetof(ScfEconn, cids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scf_econn__field_indices_by_name[] = {
  1,   /* field[1] = cids */
  0,   /* field[0] = lid */
};
static const ProtobufCIntRange scf_econn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor scf_econn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scf_econn",
  "ScfEconn",
  "ScfEconn",
  "",
  sizeof(ScfEconn),
  2,
  scf_econn__field_descriptors,
  scf_econn__field_indices_by_name,
  1,  scf_econn__number_ranges,
  (ProtobufCMessageInit) scf_econn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scf_eline__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEline, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pins",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ScfEline, n_pins),
    offsetof(ScfEline, pins),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEline, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conns",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEline, n_conns),
    offsetof(ScfEline, conns),
    &scf_econn__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lines",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEline, n_lines),
    offsetof(ScfEline, lines),
    &scf_line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scf_eline__field_indices_by_name[] = {
  3,   /* field[3] = conns */
  2,   /* field[2] = flags */
  0,   /* field[0] = id */
  4,   /* field[4] = lines */
  1,   /* field[1] = pins */
};
static const ProtobufCIntRange scf_eline__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor scf_eline__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scf_eline",
  "ScfEline",
  "ScfEline",
  "",
  sizeof(ScfEline),
  5,
  scf_eline__field_descriptors,
  scf_eline__field_indices_by_name,
  1,  scf_eline__number_ranges,
  (ProtobufCMessageInit) scf_eline__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scf_ecomponent__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pins",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEcomponent, n_pins),
    offsetof(ScfEcomponent, pins),
    &scf_epin__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEcomponent, h),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scf_ecomponent__field_indices_by_name[] = {
  6,   /* field[6] = h */
  0,   /* field[0] = id */
  2,   /* field[2] = pins */
  1,   /* field[1] = type */
  5,   /* field[5] = w */
  3,   /* field[3] = x */
  4,   /* field[4] = y */
};
static const ProtobufCIntRange scf_ecomponent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor scf_ecomponent__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scf_ecomponent",
  "ScfEcomponent",
  "ScfEcomponent",
  "",
  sizeof(ScfEcomponent),
  7,
  scf_ecomponent__field_descriptors,
  scf_ecomponent__field_indices_by_name,
  1,  scf_ecomponent__number_ranges,
  (ProtobufCMessageInit) scf_ecomponent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scf_efunction__field_descriptors[7] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "components",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEfunction, n_components),
    offsetof(ScfEfunction, components),
    &scf_ecomponent__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elines",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEfunction, n_elines),
    offsetof(ScfEfunction, elines),
    &scf_eline__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScfEfunction, h),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scf_efunction__field_indices_by_name[] = {
  1,   /* field[1] = components */
  2,   /* field[2] = elines */
  6,   /* field[6] = h */
  0,   /* field[0] = name */
  5,   /* field[5] = w */
  3,   /* field[3] = x */
  4,   /* field[4] = y */
};
static const ProtobufCIntRange scf_efunction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor scf_efunction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scf_efunction",
  "ScfEfunction",
  "ScfEfunction",
  "",
  sizeof(ScfEfunction),
  7,
  scf_efunction__field_descriptors,
  scf_efunction__field_indices_by_name,
  1,  scf_efunction__number_ranges,
  (ProtobufCMessageInit) scf_efunction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scf_eboard__field_descriptors[1] =
{
  {
    "functions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScfEboard, n_functions),
    offsetof(ScfEboard, functions),
    &scf_efunction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scf_eboard__field_indices_by_name[] = {
  0,   /* field[0] = functions */
};
static const ProtobufCIntRange scf_eboard__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor scf_eboard__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scf_eboard",
  "ScfEboard",
  "ScfEboard",
  "",
  sizeof(ScfEboard),
  1,
  scf_eboard__field_descriptors,
  scf_eboard__field_indices_by_name,
  1,  scf_eboard__number_ranges,
  (ProtobufCMessageInit) scf_eboard__init,
  NULL,NULL,NULL    /* reserved[123] */
};
